### ISSUE TITLE
Invalid bundle.

### ISSUE THREAD

**Issue by ashishagrawal0108** [LoginRadius/ios-sdk#2]
Hi LoginRadius Team,
I'm using your 'LRSDK' in my iOS Application, every thing is working properly but when I try to upload my app on iTune Connect using Xcode( v - 7.3.1), It gives me below errors

 `When I directly download & use LRSDK framework`

> <img src="http://s31.postimg.org/e14lj07s9/Screen_Shot_2016_07_22_at_6_53_04_PM.png" width="1052" height="618" />

`When I used LRSDK using Carthage dependency manager`

> <img src="https://s31.postimg.org/5k538333f/Screen_Shot_2016_07_25_at_4_38_02_PM.png" width="582" height="384" />

Please suggest me what should I do to get ride out of this.
Thanks In advance.

**Comment by ravitejag** [comment]
@ashishagrawal0108 You can try deleting the Frameworks folder in LRSDK.Framework and upload it.
This will not affect the app in anyway.

**Comment by ashishagrawal0108** [comment]
@ravitejag thanks to reply, But still I didn't get success to upload my app. I have also disabled  `BitCode`  and then tried but unfortunately it gives below errors 

> <img src="http://i.imgur.com/hBE2n8o.png" />

**Comment by ravitejag** [comment]
Support for CocoaPods is added in the latest version. Tested by uploading a sample app to iTunesConnect and it's working. Follow the instructions in README.md to setup cocoapod and install LRSDK.

**Comment by ravitejag** [comment]
closing the issue. Will take it forward from support.
