### ISSUE TITLE
Login issue  

### ISSUE THREAD

**Issue by ashishagrawal0108** [LoginRadius/ios-sdk#3]
Hi LoginRadius Team,

I'm using your SDK for Social login because I want to all social login support on my iOS App & try to login with Facebook and Google+and for other social provider too, but I did not get success to login It always showing below error have a look and suggest me what should I do ? 

Note: - Facebook and Google +, I have configured social login settings on my LoginRadius account.

> <img src="https://uploads.intercomcdn.com/i/o/10071027/45b4d40ffdba2dbfeb24efc8/Simulator%20Screen%20Shot%2003-Sep-2016,%205.14.23%20PM.png" width="375" height="667" />

Regards 
Ashish

**Comment by Karl-LoginRadius** [comment]
Hi Ashish, 

We have responded to this via our support channel, as this is not an SDK issue I will close this thread.
Thanks,
