### ISSUE TITLE
xcode 9 compatibility

### ISSUE THREAD

**Issue by Basca** [LoginRadius/ios-sdk#5]
The SDK is currently not compatible with xcode 9.
There is one reference that causes it to not compile:
https://github.com/LoginRadius/ios-sdk/blob/cb8d4d6f056986a8594d349e5e60421d166e2b77/Sources/LoginRadiusSDK.m#L80

Causing the following error:
![screen shot 2017-10-09 at 14 03 00](https://user-images.githubusercontent.com/4748353/31337218-994e12d4-acfa-11e7-9efd-80f52ded14b6.png)

By replacing self to the actual class name as the functions below do, it can be fixed:
`    [[[LoginRadiusSDK sharedInstance] session] logout];`

Could you please make this change?

**Comment by tsanjoto** [comment]
Hi, the fix for XCode 9 compatible is on QA at the moment, as it include some other fixes and improvements.
It will be released soon.

**Comment by tsanjoto** [comment]
Hi Basca,
the XCode9 Compatibility is now live. On version 4.1.0
